version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: "2g"
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 10s
      retries: 5

  tests:
    build: .
    working_dir: /app
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      CI: "true"
      SELENIDE_REMOTE_URL: http://selenium:4444/wd/hub
    volumes:
        - ./allure-results:/app/allure-results
        - ./cucumber-report:/app/cucumber-report
        - ./target:/app/target
    command: mvn test -Dselenide.remote=http://selenium:4444/wd/hub
